version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5713:80"  # Map host port 5713 to container port 80 (Nginx)
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:5000"  # Map host port 3000 to container port 5000 (Express)
    environment:
      NODE_ENV: production
      # Add any other backend environment variables here